backend:
  name: github                  # set to 'git-gateway' when using neltlify git-gateway
  repo: ReInHerit/digital-hub   # comment out line when using neltlify git-gateway
  branch: main
local_backend: true             # true if accessed local dev instance of netlify cms port 8081 | How tu run a local dev server: https://www.netlifycms.org/docs/beta-features/
search: false   # disables search for collections -> hidden collections could be found with other config!
logo_url: /images/rein_logo.jpg   # setting a custom logo used by the CMS. Displayed ad login screen.

media_folder: "images/uploads"
# next two lines are only necessery if media should be deactivated
media_library:      # comment out will make media available.
  name: 'disabled'  # comment out will make media available.

# for open authoring / kanban view for moderation processes
# warning -> still in beta!
# https://www.netlifycms.org/docs/open-authoring/#enabling-open-authoring
# publish_mode: editorial_workflow   

# collections config see here: https://www.netlifycms.org/docs/widgets/#object
collections:
  - name: "tools"
    label: "WP3-Toolkit: Tools"
    label_singular: 'tool'
    hide: false                # hides specific collection -> still available if you have the link!
    folder: "content/tools"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "tools" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Link", name: "link", widget: "string"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Training available", name: "training available", widget: "boolean", default: false}
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Type", name: "tool-type", widget: "select", options: ["REST-API", "Library", "Web-Interface","GraphQL-API","Application","CLI","Python","Java","X-Technologies","Javascript","Typescript","Web Development","Economics","Cultural Heritage","History","Museology","Machine Learning","Topic Modeling","NLP","GIS","Relational DB"], default: ["NLP"], multiple: true, required: true }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tutorial", name: "tutorial", widget: "markdown" }
  - name: "training"
    label: "WP3: Training"
    label_singular: 'entry'
    hide: true                # hides specific collection -> still available if you have the link!
    folder: "content/training"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "training" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Type", name: "training-type", widget: "select", options: ["WEBINAR", "COURSE"], default: ["WEBINAR"], multiple: true, required: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "apps"
    label: "WP3: Apps"
    label_singular: "app"
    hide: true                # hides specific collection -> still available if you have the link!
    folder: "content/apps"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "training" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Type", name: "training-type", widget: "select", options: ["WEBINAR", "COURSE"], default: ["WEBINAR"], multiple: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "games"
    label: "WP3: Games"
    label_singular: "game"
    hide: true                # hides specific collection -> still available if you have the link!
    folder: "content/games"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Type", name: "type", widget: "hidden", default: "training" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Type", name: "training-type", widget: "select", options: ["WEBINAR", "COURSE"], default: ["WEBINAR"], multiple: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "code"
    label: "Code-snippets"
    hide: true                # hides specific collection -> still available if you have the link!
    folder: "content/code"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Code", name: "code", widget: "code" }
  - name: "performances"
    label: "WP4: Performances"
    label_singular: "performance"
    hide: false                # hides specific collection -> still available if you have the link!
    folder: "content/performances"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Type", name: "type", widget: "hidden", default: "performance" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "exhibitions"
    label: "WP6: Digital exhibitions"
    label_singular: 'exhibition'
    hide: false                # hides specific collection -> still available if you have the link!
    folder: "content/exhibitions"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      # - { label: "Code", name: "code", widget: "code" }
  - name: "news"
    label: "WP7: News"             # Used in the UI
    label_singular: 'message' # Used in the UI, ie: "New Post"
    folder: "content/news"
    description: Here you may provide all your news posts etc... Make sure that you have ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.
    create: true              # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Type", name: "type", widget: "hidden", default: "news" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author(s)", name: "author", widget: "select", options: ["sina", "chiara","project"], default: "project", multiple: true }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "designs"
    label: "WP?: Designs"
    label_singular: "design"
    hide: false                # hides specific collection -> still available if you have the link!
    folder: "content/designs"
    description: E-Shop items
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "blog" }
      - { label: "Type", name: "type", widget: "hidden", default: "design" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Target Audience", name: "target-audience", widget: "select", options: ["VISITOR", "PROFESSIONAL"], default: ["VISITOR"], multiple: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Pages"
    name: "pages"
    hide: true # hides specific collection -> still available if you have the link!
    files:
      - label: "About Page"
        name: "about"
        file: "static/sites/about.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
      - label: "Locations Page"
        name: "locations"
        file: "static/sites/locations.json"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Locations
            name: locations
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Address, name: address, widget: string}